version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: dockerfile
        container_name: nextstore_app
        ports:
            - "2027:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=store_db
            - DB_USERNAME=phpmyadmin
            - DB_PASSWORD=300102

    db:
        image: mysql:8.3
        container_name: mysql_db
        restart: unless-stopped
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: store_db
            MYSQL_USER: phpmyadmin
            MYSQL_PASSWORD: 300102
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
